development:
  adapter: postgresql
  encoding: utf8
  database: task_manager_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: task_manager_test
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: task_manager_production
  username: postgres
  password: postgres
  host: localhost